name: "CI (Build)"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-unix:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cc: [gcc, clang]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          key: neomake-install-main
      - name: Install neomake
        run: |
          cargo install --locked --git https://github.com/sinisterMage/neomake.git --rev main neomake
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - name: Build and Run Tests
        run: CC=${{ matrix.cc }} neomake run test cli

  build-windows:
    name: Build (Windows - MSVC)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build Library
        run: .\build.bat