name: "Security Scan"

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 5 * * 1' # every monday at 05:30AM

jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'c'
      - name: Build
        run: make all
      - name: Perform Analysis
        uses: github/codeql-action/analyze@v3