name: "Security Scan"

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 5 * * 1' # every monday at 05:30AM

jobs:
  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          key: neomake-install-main
      - name: Install neomake
        run: |
          cargo install --locked --git https://github.com/sinisterMage/neomake.git
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'c'
      - name: Install cppcheck
        run: sudo apt-get install cppcheck
      - name: Build
        run: neomake run all
      - name: Perform Analysis
        uses: github/codeql-action/analyze@v3